name: local-coder
version: 0.0.1
schema: v1

models:
    - name: Local Coder
      provider: ollama
      model: "{{cookiecutter.local_model}}"
      apiBase: http://ollama:11434
      roles:
        - chat
        - edit
        - autocomplete
        